config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'

  resources :lists, execpt: %i[index] do
    resources :bookmarks, only: %i[index new create]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, :list_id, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  # has_many :lists, through: :bookmarks
  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @list_id = params[:list_id]
    @bookmarks = Bookmark.all.where(list_id: @list_id)
    # raise
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @movie_choices = Movie.all
    @list_choices = List.all
    # raise
  end

  def create
    # raise
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    # raise
    if @bookmark.save
      redirect_to list_path(@list[:id])
    else
      render 'new'
    end
    # raise
  end


  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
    # raise
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to @list
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render 'new'
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/index.html.erb
<h1>Your bookmarks</h1>
<ul>
  <% @bookmarks.each do |bookmark| %>
    <li>
      <p>Name of movie:<%= bookmark.movie.title %></p>
      <p>comment:<%= bookmark.comment %></p><br>
    </li>
  <% end %>
</ul>

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 mx-auto">
      <%= simple_form_for ([@list, @bookmark]) do |f| %>
        <%= f.input :comment %>
        <%= f.input :movie_id, collection: @movie_choices, value_method: :id %>
        <%# <%= f.input :list_id, value="#{@list.id}" %> %>
        <%= f.submit "Submit new Bookmark", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<h2>Create new Bookmark</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">

        <%= yield %>

      </div>
    </div>
  </body>
</html>

app/views/lists/edit.html.erb
<h2>Edit your List</h2>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit Changes", class: "btn btn-primary" %>
<% end %>

app/views/lists/index.html.erb
<h1>Movie Lists</h1>
<%= link_to "New!", new_list_path %>
<div class="row">
  <%# <ul> %>
    <% @lists.each do |list| %>
      <%# <li> %>
      <div class="col-12 col-md-4 col-xl-3">
        <div class="card" style="width: 18rem;">
          <% if list.photo.attached? %>
            <%= cl_image_tag list.photo.key, class: "card-img-top", alt:"sweet seo" %>
          <% end %>
          <div class="card-body">
            <h3><%= link_to list.name, list, class:"text-decoration-none" %></h3>
            <div class="d-flex justify-content-between">
              <p><%= link_to 'edit', edit_list_path(list), class:"btn btn-outline-warning btn-sm" %></p>
              <p><%= link_to 'delete',
                lists_path(list),
                method: :destroy,
                data: { confirm: "Are you sure?" },
                class:"btn btn-outline-danger btn-sm" %></p>
            </div>
          </div>
        </div>
      </div>
      <%# </li> %>
    <% end %>
  <%# </ul> %>
</div>

app/views/lists/new.html.erb
<h2>Create new List</h2>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit new list", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<div>
  <%# style="background-image: url(<%= cl_image_path(@list.photo.key)%>
  <% if @list.photo.attached? %>
    <%= cl_image_tag @list.photo.key%>
  <% end %>
  <h1 class="display-4 text-white"><%= @list.name %></h1>
  <%= link_to "delete",
    list_path(@list),
    method: :delete,
    data: { confirm: "Are you sure?" } %>
  <%= link_to "edit", edit_list_path %>
</div>


<ul>
  <% @bookmarks.each do |bookmark| %>
    <li> <%= bookmark.comment %> <br>
    <%= bookmark.movie.title %> <br>
    <%= link_to "delete",
      bookmark_path(bookmark),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
  </li>
  <% end %>
</ul>

<%= link_to "add bookmark", new_list_bookmark_path(@list)  %>

<%= link_to "back", lists_path  %>